[server]
port = 8501
address = "0.0.0.0"
headless = true
runOnSave = true
allowRunOnSave = true
enableCORS = true
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "light"